export const appConstants = {
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  CLEAR_SNACKBAR:"CLEAR_SNACKBAR",
  SET_BACKDROP:"SET_BACKDROP",
  SET_NAVBAR:"SET_NAVBAR"
}

export const loggerConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  ACTIVITIES_REPORT: "ACTIVITIES_REPORT",
  SET_END_DATE: "SET_END_DATE",
  SET_START_DATE: "SET_START_DATE"
}

export const taigaTypes = {
  TAIGA_LOGIN: "TAIGA_LOGIN",
  TAIGA_SET_PROJECTS: "TAIGA_SET_PROJECTS",
  SET_STORIES: "SET_STORIES",
  TAIGA_LOGOUT: "TAIGA_LOGOUT",
  TAIGA_CLEAN: "TAIGA_CLEAN"
}

export const sonarTypes = {
  SONAR_LOGIN: "SONAR_LOGIN",
  SONAR_CLEAN: "SONAR_CLEAN",
  SONAR_SET_PROJECTS: "SONAR_SET_PROJECTS",
  SET_SONAR_TOKEN: "SET_SONAR_TOKEN"
}

export const gitlabConstants = {
  SET_GITLAB_TOKEN:"SET_GITLAB_TOKEN",
  GITLAB_REPORT:"GITLAB_REPORT",
  DEVEL_STATS:"DEVEL_STATS",
  SET_GITLAB_MENU_INDEX:"SET_GITLAB_MENU_INDEX",
  SET_REPOSITORY_INDEX:"SET_REPOSITORY_INDEX",
  SET_GITLAB_VIEW:"SET_GITLAB_VIEW"
}

export const mattermostConstants = {
  INCREASE_COUNTER:"INCREASE_COUNTER",
  MATTERMOST_LOGOUT:"MATTERMOST_LOGOUT",
  SET_CHANNELS:"SET_CHANNELS",
  SET_MATTERMOST_TOKEN:"SET_MATTERMOST_TOKEN",
  SET_MATTERMOST_MENU_INDEX:"SET_MATTERMOST_MENU_INDEX",
  SET_MESSAGES:"SET_MESSAGES",
  SET_TEAM_ID:"SET_TEAM_ID",
  SET_TEAMS:"SET_TEAMS"
}
