export const userConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  ACTIVITIES_REPORT: "ACTIVITIES_REPORT",
  SET_END_DATE: "SET_END_DATE",
  SET_START_DATE: "SET_START_DATE",
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  CLEAR_SNACKBAR:"CLEAR_SNACKBAR",
  CLOSE_BACKDROP:"CLOSE_BACKDROP",
  SET_NAVBAR:"SET_NAVBAR",
  SET_GITLAB_TOKEN:"SET_GITLAB_TOKEN",
  GITLAB_REPORT:"GITLAB_REPORT",
  SET_GITLAB_INDEX:"SET_GITLAB_INDEX"
}
