export const appConstants = {
  SEND_NOTIFICATION: "SEND_NOTIFICATION",
  CLEAR_SNACKBAR:"CLEAR_SNACKBAR",
  SET_BACKDROP:"SET_BACKDROP",
  SET_NAVBAR:"SET_NAVBAR"
}

export const loggerConstants = {
  LOGIN_SUCCESS: "LOGIN_SUCCESS",
  LOGIN_ERROR: "LOGIN_ERROR",
  LOGOUT: "LOGOUT",
  REGISTER_SUCCESS: "REGISTER_SUCCESS",
  REGISTER_ERROR: "REGISTER_ERROR",
  ACTIVITIES_REPORT: "ACTIVITIES_REPORT",
  SET_END_DATE: "SET_END_DATE",
  SET_START_DATE: "SET_START_DATE"
}

export const gitlabConstants = {
  SET_GITLAB_TOKEN:"SET_GITLAB_TOKEN",
  GITLAB_REPORT:"GITLAB_REPORT",
  DEVEL_STATS:"DEVEL_STATS",
  SET_GITLAB_MENU_INDEX:"SET_GITLAB_MENU_INDEX",
  SET_REPOSITORY_INDEX:"SET_REPOSITORY_INDEX",
  SET_GITLAB_VIEW:"SET_GITLAB_VIEW"
}
