export const taigaTypes = {
  LOGIN: "LOGIN",
  TOKEN_RECEIVED: "TOKEN_RECEIVED",
  TOKEN_EXPIRED: "TOKEN_EXPIRED",
  USER_ID_RECEIVED: "USER_ID_RECEIVED",
  USER_STATS_RECEIVED: "USER_STATS_RECEIVED",
  PROJECTS_STATS_RECEIVED: "PROJECTS_STATS_RECEIVED"
}
